### ISSUE TITLE
Can not store to MongoDB

### ISSUE THREAD

**Issue by hendisantika** [realpython/realpython-blog#28]
Nice tutorial.

I have an issue.

Before I store to MongoDB it is OK.
But when I tried to store to MongoDB it is going wrong.

Could you give me an advice, please.
=======================================
Traceback (most recent call last):
  File "/home/hendisantika/Documents/python/ENV/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 91, in __init__
    self.update(values, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

=======================================

Thank you.

**Comment by mjhea0** [comment]
http://stackoverflow.com/a/37469195/1799408

**Comment by hendisantika** [comment]
I have follow the guide from stackoverflow above. But I still got nothing result except the error is gone. But the scrapy gives me nothing.

What is wrong?

Any Advice?

Thanks

**Comment by hendisantika** [comment]
Maybe you have to update your repo.
So that we can follow and try your updated repo and can see the better result.

What do you think?

Thanks
